Toy 10 camera warning
bonchangkoo/RookiePhotoApp pull request #10
Opened 2019-04-17 10:13 UTC by hyejin830

단말 센서를 이용해서 기울기에 따라 워닝 메세지가 보여지게 또는 안보여지게 구현했습니다.

2019-04-18 08:41 UTC, bonchangkoo requested changes
가속 센서가 없는 단말에 대해서 대비책이 있어야 할 거 같습니다.

2019-04-18 08:41 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/camera/CameraActivity.java
>          cameraKitView.onResume();
아까 시연할 때 여러번 동작하면 camera 뷰가 제대로 작동안하는거 같았는데요. 원인 파악이 필요할 거 같아요.

2019-04-18 08:41 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/camera/CameraActivity.java
> +    private static final float STANDARD_SENSOR_LOACTION = 5.0f;
값이 5.0f 인 의미가 있는건가요?

2019-04-18 08:52 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/camera/CameraActivity.java
> +    private static final float STANDARD_SENSOR_LOACTION = 5.0f;
가로와 세로모드를 구분 짓는 정확한 기울기 지점이 정확하지 않아서, 일단은 임의로 5 값으로 설정했습니다.

2019-04-18 08:55 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/camera/CameraActivity.java
>          cameraKitView.onResume();
이 부분은 병용님과 작업한 부분이므로 함께 의논해보겠습니다.

2019-04-22 03:15 UTC, hyejin830 commented
@bonchangkoo @pby2017 이전에 구현했던 센서 값에 따른 워닝 메세지 구현 부분은 삭제했고, CameraActivity의 Manifest 파일에 속성 세로모드로 고정되게 하였습니다.

2019-04-22 04:38 UTC, bonchangkoo approved these changes
코드 확인했습니다.

2019-04-22 06:11 UTC, pby2017 approved these changes
코드 확인했습니다.

2019-04-22 07:40 UTC, merged