Toy 16 captured photo preview
bonchangkoo/RookiePhotoApp pull request #11
Opened 2019-05-02 03:05 UTC by hyejin830

[촬영한 사진 보여주는 프리뷰 페이지 구현]
- activity_preview.xml 레이아웃 수정 및 뒤로버튼과 편집 버튼 추가
- 뒤로 버튼 누를 시, 메인으로 이동
- 편집 버튼 누를 시, 추후에 작업 예정
- 필요없는 import 삭제하였고, 네이밍 수정하였습니다

코드리뷰 부탁드립니다~

2019-05-02 05:32 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/camera/capture/PreviewActivity.java
> +    private Bitmap capturedImageBitmap;
메모리 관리 차원에서 bitmap 객체는 다음과 같이 메모리 할당 해제를 해주는 편이 좋습니다.

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (capturedImageBitmap !=  && !capturedImageBitmap.isRecycled()) {
            capturedImageBitmap.recycle();
        }
    }

2019-05-02 05:33 UTC, bonchangkoo requested changes
확인 부탁드립니다.

2019-05-07 02:53 UTC, hyejin830 commented
1. 병용님과의 충돌 코드를 수정했습니다

2. bitmap 메모리 할당 해제 코드 추가하였습니다.

2019-05-07 03:25 UTC, pby2017 approved these changes
코드 확인했습니다~!

2019-05-07 05:41 UTC, merged