Toy 18 편집된 사진 보기 및 다운로드 기능
bonchangkoo/RookiePhotoApp pull request #16
Opened 2019-05-09 01:47 UTC by hyejin830

편집한 사진을 보기 및 갤러리에 저장 기능 제공합니다

## 추가 사항

### 1. 편집 결과 화면 생성 및 Intent 구현
- 편집한 결과를 보여줄 EditResultActivity를 생성했습니다
- EditPhotoActivity에서 편집 완료(V)를 누를 시 결과 화면으로 이동하게 구현했습니다

### 2. 사진 저장
- Uri와 File 스트림을 이용하여 구현하였습니다.

### 3. Warning 해결
- 두가지의 워닝 부분을 해결하였습니다.
- mkdirs 워닝 부분에 대해서는 방법을 찾아보았으나 아직은 미해결 상태입니다.

## 변경 사항

### 1. 툴바 아이콘 벡터 드로어블에서 PNG로 변경 및 왼쪽 버튼(다이어리 작성) 이미지 변경
- 벡터 드로어블이 Android 4.4(API 레벨 20)이하는 지원하지 않기 때문에 PNG로 수정하는 작업하였습니다
- 아이콘의 경우 https://material.io/tools/icons 사이트를 참고하였습니다
- 툴바 왼쪽에 다이어리 작성 버튼이 있어야 함으로 기존에 왼쪽 버튼(home)의 이미지를 변경하였고, 추후 menu가 home인 부분을 다이어리로 이동하게 구현할 예정입니다. (참고한 사이트 :https://eskeptor.tistory.com/61)

### 2. EditPhotoActivity에서 읽기,쓰기 권한 허가로 변경
- 갤러리 선택에서 읽기 권한만 허가한 후, 저장할 때 쓰기 기능 권한을 얻으려고 시도하였으나 이미 저장공간을 허가한 상태이기 때문에 팝업이 뜨지 않는 상황이 발생하였습니다.
- 그러하여 갤러리 선택을 할 때 권한 허가하는 경우 READ_EXTERNAL_STORAGE와 WRITE_EXTERNAL_STORAGE 모두 권한 허가하는 것으로 변경하였습니다.

** 병용님의 처음에 권한 허가하는 부분과 머지가 안된 부분이라, 추후에 병용님과 상의해서 어떻게 할 것인지 정할 예정입니다

### 3. EditPhotoActiivity data null 처리
- 편집 완료로 이동할 때 data null처리를 하였고, null일 경우 toast 띄우는 형태로 변경하였습니다

2019-05-09 01:58 UTC, hyejin830 commented
@pby2017 님 코드리뷰 부탁드립니다.

2019-05-09 05:45 UTC, pby2017 commented on app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
`tools:ignore="GoogleAppIndexingWarning"`
이 코드는 어떤 역할을 하는지 궁금합니다.

그리고 개발할 때 
잠깐 선언하는 것인지 아니면 영구적으로 선언하는 것인지
궁금합니다.

2019-05-09 05:52 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditPhotoActivity.java
> +            EditResultActivity.startWithUri(EditPhotoActivity.this, resultUri);
이 부분에서 Intent 생성과 startActivity() 메서드 호출이 정의되지 않고

`EditResultActivity` 안에
startActivity()가 정의된 `static void startWithUri()` 메서드를 호출하는 이유가 궁금합니다.

2019-05-09 05:59 UTC, hyejin830 commented on app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
warning이 있어 추천에 의해 추가하였고 동작하는데 문제가 없어서 두었습니다.
자세히 알아보니,
앱을 더 최적화 할 수 있는 방법을 알려주기 위한 설정 방법으로 App link Indexing 기능을 사용하라는 경고라고 하네요.

혹시 문제가 된다고 생각하시거나 추가할 필요가 없다고 생각하시면 삭제하겠습니다.

2019-05-09 06:03 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditPhotoActivity.java
> +            EditResultActivity.startWithUri(EditPhotoActivity.this, resultUri);
방법의 차이인 것 같습니다. 저 코드 부분은 샘플을 참고해서 구현했습니다.

2019-05-10 02:09 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditPhotoActivity.java
> +                && ActivityCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)
2개 permission이 `GRANTED` 인지에 대한 연결이 && 으로 되어있는데

1개의 permission만 `GRANTED` 임을 만족하면 
나머지 1개의 permission에 대해서는 request를 호출하지 않는 것 같습니다.

2019-05-10 02:32 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +            YogiDiaryStorageDir.mkdirs();
검색했을 때 제일 상단에 있는 글이라 찾아보셨던 글일 것 같아요 
[stackoverflow 링크](https://stackoverflow.com/a/36217180)

디렉토리를 새로 생성했을 때랑 생성하지 않았을 때 로직이 구분되어야 할 게 당장은 떠오르지 않네요.
임시로 생성 여부에 따라 로그 출력을 하는 것으로 워닝을 안보이게할 수는 있어보입니다.
```
if(!exists()){
    if(mkdirs(){
        Log.d(생성 성공...);
    } else {
        Log.d(생성 실패...);
    }
} else {
    Log.d(이미 존재...);
}

2019-05-10 03:19 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +            YogiDiaryStorageDir.mkdirs();
아 네 저도 이 글은 보았습니다. 다시 로직 생각을 해보고 수정해보도록 하겠습니다. 감사합니다

2019-05-10 03:28 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditPhotoActivity.java
> +                && ActivityCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)
네 오류가 나고, 저장이 되지 않습니다. 쓰기 권한을 같이 허가해줘야 할 것 같습니다.

2019-05-13 04:44 UTC, bonchangkoo reviewed
사진 찍고나서 편집 화면 눌렀을 때 아무런 동작이 없는데 원래 이런거에요?

2019-05-13 04:57 UTC, hyejin830 commented
@bonchangkoo  넵 맞습니다. 촬영한 사진의 편집은 3시간 전에 머지 했고, 
이 브랜치는 사진 선택해서 편집한 뒤 저장하는 코드 구현입니다!

2019-05-13 04:59 UTC, bonchangkoo commented on app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
이거는 없어도 괜찮을 거 같아요.

2019-05-13 05:01 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +    public boolean onCreateOptionsMenu(final Menu menu) {
화면을 못봐서 그러는데... onCreateOptionsMenu가 필요한거에요?

2019-05-13 05:02 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +        File YogiDiaryStorageDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "YogiDiary");
변수명 컨벤션 지켜주세염

2019-05-13 05:07 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +            actionBar.setTitle(getString(R.string.format_crop_result_d_d, options.outWidth, options.outHeight));
타이틀에 사진 크기를 꼭 포함해야하는건가요? 사진 사이즈 얻어오려고 BitmapFactory.decodeFile() 하는건 다소 비효율적인거 같네요.

2019-05-13 05:08 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +    public boolean onCreateOptionsMenu(final Menu menu) {
툴바에 다운로드 버튼이 있습니다.

2019-05-13 05:09 UTC, bonchangkoo requested changes
UCropView는 불필요한거 같네요~ 확인 부탁드립니다.

2019-05-13 05:10 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +            actionBar.setTitle(getString(R.string.format_crop_result_d_d, options.outWidth, options.outHeight));
아니요 샘플을 참고하면서 가져온 부분인데, 삭제하겠습니다.

2019-05-13 05:10 UTC, hyejin830 commented
@bonchangkoo 네 알겠습니다

2019-05-13 05:14 UTC, hyejin830 commented on app/src/main/AndroidManifest.xml
> +        tools:ignore="GoogleAppIndexingWarning">
넵 삭제하겠습니다.

2019-05-13 06:10 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/edit/EditResultActivity.java
> +        File YogiDiaryStorageDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "YogiDiary");
알겠습니다. 수정하겠습니다.

2019-05-13 06:23 UTC, hyejin830 commented
@pby2017 @bonchangkoo 코드 리뷰 사항 반영해서 수정하였습니다.

2019-05-13 06:30 UTC, bonchangkoo approved these changes
코드 확인했습니다.

2019-05-13 06:56 UTC, pby2017 approved these changes
코드 확인했습니다.

2019-05-13 07:03 UTC, merged