TOY-56 다이어리 메인화면 MVVM + Kotlin 변환
bonchangkoo/RookiePhotoApp pull request #32
Opened 2019-06-12 04:21 UTC by pby2017

코드 리뷰 부탁드립니다.
- 메인 화면 MVVM + Kotlin 변환
- 달력으로 화면 이동 구현
- 다이어리 시간 최신 순서 우선으로 정렬

2019-06-14 01:30 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/BaseActivity.kt
> +    fun buildCalendarDialog(calendar: Calendar, listener: DatePickerDialog.OnDateSetListener): YearMonthPickerDialog {
다이어리 메인에서만 사용할 것 같은데 BaseActivity에 작성한 이유가 따로 있을까요?!

2019-06-14 01:31 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesActivity.kt
> +        setContentView(R.layout.activity_diaries)
이 부분은 없어도 되지 않을까요?!

2019-06-14 03:20 UTC, KimSoungRyoul commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesActivity.kt
> +import java.util.*
필요한 아이들만 import해주는게 좋을 것 같아요
### Avoid import * !!!
https://stackoverflow.com/questions/22000507/java-avoid-repeated-import-not-inherit-import

2019-06-14 05:42 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/BaseActivity.kt
> +    fun addProgressBarInto(layout: ViewGroup) {
이거 그냥 로딩뷰 보여주는건가요?

2019-06-14 05:43 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/BaseActivity.kt
> +    fun addProgressBarInto(layout: ViewGroup) {
로딩뷰를 위한거라면 로딩뷰를 DialogFragment로 처리하도록 해요~

2019-06-14 05:44 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesActivity.kt
> +class DiariesActivity : BaseActivity(), DatePickerDialog.OnDateSetListener {
뷰모델 쓰는데 listener가 왜 있는거에요?

2019-06-14 05:46 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +    private var hourMinuteFormat = SimpleDateFormat("hh:mm", Locale.getDefault())
var 이어야 하는 이유가 있어요? 그리고 by lazy로 써도 될거 같아요.

2019-06-14 05:46 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +    private var dayFormat = SimpleDateFormat("dd일", Locale.getDefault())
위에랑 마찬가지

2019-06-14 05:47 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +        diariesViewHolder.dayText.text = dayFormat.format(calendar.time)
diariesViewHolder.run { } 으로 묶어서 써보세요.

2019-06-14 05:48 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +                val intent = Intent(context, DiaryDetailActivity::class.java)
.apply { } 적용해보세요~

2019-06-14 05:50 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +        diariesViewModel = ViewModelProviders.of((context as DiariesActivity)).get(DiariesViewModel::class.java)
context as DiariesActivity -> this

`    @NonNull
    @MainThread
    public static ViewModelProvider of(@NonNull Fragment fragment, @Nullable Factory factory) {
        Application application = checkApplication(checkActivity(fragment));
        if (factory == null) {
            factory = ViewModelProvider.AndroidViewModelFactory.getInstance(application);
        }
        return new ViewModelProvider(ViewModelStores.of(fragment), factory);
    }`

모르는 함수 호출할 때는 어떻게 쓰는지 먼저 확인부터하는 습관을 들이세요.

2019-06-14 05:51 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +            val linearLayoutManager = LinearLayoutManager(context)
```suggestion
            layoutManager = LinearLayoutManager(context)
            adapter = DiariesAdapter(context, ArrayList())
```

불필요한 코드는 줄입시다...

2019-06-14 05:52 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +            val bundle = Bundle()
```suggestion
            val bundle = Bundle().apply { ... }
```

apply 써보도록 하세

2019-06-14 05:53 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesViewModel.kt
> +        val calendar = GregorianCalendar()
apply { ... } 적용해보세요.

2019-06-14 05:54 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesViewModel.kt
> +        val calendar = Calendar.getInstance()
apply { ... } 적용해보세요.

2019-06-14 05:55 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            yearPicker = view.findViewById<NumberPicker>(R.id.picker_year).apply {
코틀린에서는 findViewById를 쓸일이 없어요...

 view.picker_year.apply { }

2019-06-14 05:55 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            monthPicker = view.findViewById<NumberPicker>(R.id.picker_month).apply {
코틀린에서는 findViewById를 쓸일이 없어요. (2)

2019-06-14 05:55 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            confirmButton = view.findViewById<Button>(R.id.btn_confirm).apply {
코틀린에서는 findViewById를 쓸일이 없어요. (3)

2019-06-14 05:55 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            cancelButton = view.findViewById<Button>(R.id.btn_cancel).apply {
코틀린에서는 findViewById를 쓸일이 없어요. (4)

2019-06-14 05:56 UTC, bonchangkoo requested changes
리뷰 확인 부탁드려요~

2019-06-17 06:20 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/BaseActivity.kt
> +    fun buildCalendarDialog(calendar: Calendar, listener: DatePickerDialog.OnDateSetListener): YearMonthPickerDialog {
Dialog 라는 이름 때문에 아직 없지만 다른 곳에서도 사용할 수 있을 것이라고 생각해서 BaseActivity에 작성했는데,
현재는 달력 다이얼로그가 필요한 클래스 파일은 다이어리 메인 밖에 없어서 
다이어리 메인으로 옮기도록 하겠습니다.

2019-06-17 06:20 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesActivity.kt
> +        setContentView(R.layout.activity_diaries)
네,
없어도 되는 코드입니다. 삭제하겠습니다.

2019-06-17 06:25 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesActivity.kt
> +import java.util.*
네,
꼭 확인하겠습니다.

2019-06-17 06:34 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +    private var hourMinuteFormat = SimpleDateFormat("hh:mm", Locale.getDefault())
아뇨 없습니다.
`val`과 `by lazy` 사용해서 수정하겠습니다.

2019-06-17 06:35 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +    private var dayFormat = SimpleDateFormat("dd일", Locale.getDefault())
네,
`val`과 `by lazy` 사용해서 수정하겠습니다.

2019-06-17 06:39 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +        diariesViewHolder.dayText.text = dayFormat.format(calendar.time)
네,
수정하겠습니다.

2019-06-17 06:41 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +                val intent = Intent(context, DiaryDetailActivity::class.java)
네,
반영하겠습니다.

2019-06-17 06:47 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +            val bundle = Bundle()
네,
반영하겠습니다.

2019-06-17 06:49 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesViewModel.kt
> +        val calendar = GregorianCalendar()
네,
반영하겠습니다.

2019-06-17 06:49 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesViewModel.kt
> +        val calendar = Calendar.getInstance()
네,
반영하겠습니다.

2019-06-17 06:54 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            yearPicker = view.findViewById<NumberPicker>(R.id.picker_year).apply {
네,
반영하겠습니다.

`view.` 없이 picker_year 만 사용했을 때 null이 표시되서 
`view.` 를 사용하면서 자바 코드처럼 작성했었습니다.
숙지하겠습니다.

2019-06-17 06:55 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            monthPicker = view.findViewById<NumberPicker>(R.id.picker_month).apply {
네,
반영하겠습니다.

2019-06-17 06:55 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            confirmButton = view.findViewById<Button>(R.id.btn_confirm).apply {
네,
반영하겠습니다.

2019-06-17 06:55 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/YearMonthPickerDialog.kt
> +            cancelButton = view.findViewById<Button>(R.id.btn_cancel).apply {
네,
반영하겠습니다.

2019-06-18 02:00 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/BaseActivity.kt
> +    fun addProgressBarInto(layout: ViewGroup) {
네, 
DialogFragment 로 구현해서 처리하겠습니다.

2019-06-18 02:00 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesActivity.kt
> +class DiariesActivity : BaseActivity(), DatePickerDialog.OnDateSetListener {
날짜를 선택하는 다이얼로그 PickerDialog 의 날짜 선택 결과를 되돌려 받아 해당 날짜의 페이지로 이동하기 위해 Listener를 사용했습니다. 

무명 객체로 Listener를 구현해서 Listener implements를 제거하겠습니다.

2019-06-18 02:03 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +        diariesViewModel = ViewModelProviders.of((context as DiariesActivity)).get(DiariesViewModel::class.java)
네, 
해당 ViewModel은 Activity에서 인스턴스화한 ViewModel을 Fragment에서도 사용하기 위해 activity로 부터 전달받은 context를 캐스팅해서 사용했었습니다. 

this (fragment)를 인자로 전달했을 때 Activity ViewModel의 hashCode와 각 Fragment들의 ViewModel의 hashCode가 모두 달라서 동일한 hashCode의 ViewModel을 사용하기 위해 context를 활용했었습니다.

해당 부분은 getActivity!! 로 수정하겠습니다.

2019-06-18 02:04 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +            val linearLayoutManager = LinearLayoutManager(context)
네, 
해당 변수는 하단의 `addItemDecoration` 설정에서 인자로 전달하고 있어서 따로 변수로 생성했습니다.

2019-06-18 05:42 UTC, pby2017 commented
@bonchangkoo 님, @hyejin830 님, @KimSoungRyoul 님,

피드백 반영 완료했습니다.

2019-06-18 05:59 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +        view.recycler_diaries.apply {
apply -> run 이 더 적당한거 같아요~

apply, run, let 등등의 용법을 한번 찾아보세요~

2019-06-18 06:01 UTC, bonchangkoo commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/util/LoadingDialogFragment.kt
> +                    window!!.setBackgroundDrawableResource(android.R.color.transparent)
!! (NonNull) 이 아닌 경우도 있을 거 같아요.

2019-06-18 06:01 UTC, bonchangkoo reviewed
코멘트 확인 부탁드려요~

2019-06-18 08:17 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesFragment.kt
> +        view.recycler_diaries.apply {
네,
피드백 반영하겠습니다.

apply(T.() -> Unit)
객체 내부를 수정하고 객체를 반환할 때,

also((T) -> Unit)
 객체 내부를 수정하지 않거나 사용하지 않고 객체를 반환할 때,

let((T) -> R)
null이 아닌 객체 자신을 사용해서 코드를 실행하고 결과가 필요없거나 마지막 줄을 반환할 때,

with(receiver: T, block: T.() -> R)
run()과 비슷하면서 객체를 명시적으로 나타낼 때,

run(() -> R)
run(T.() -> R)
객체 없이 코드를 묶거나, null이 아닌 객체 내부를 수정하고 결과가 필요없거나 마지막 줄을 반환할 때

사용합니다.

2019-06-18 08:20 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/util/LoadingDialogFragment.kt
> +                    window!!.setBackgroundDrawableResource(android.R.color.transparent)
네,
!! 대신 
?.run 을 사용해서 null이 아닐 때만 코드를 실행하도록 묶었습니다.

2019-06-18 08:22 UTC, bonchangkoo approved these changes
코드 확인 했습니다.

2019-06-20 04:43 UTC, hyejin830 approved these changes

2019-06-20 04:43 UTC, hyejin830 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +                intent.putExtra("DIARY_IDX", diaries[adapterPosition].idx)
이 부분 전에 쓰던 방식과 동일하게 하시는 건 어떠신가요?!
```
val intent = Intent(context, DiaryDetailActivity::class.java).apply{
       putExtra("DIARY_IDX", diaries[adapterPosition].idx)
}          
```

2019-06-20 05:35 UTC, pby2017 commented on app/src/main/java/kr/co/yogiyo/rookiephotoapp/diary/main/DiariesAdapter.kt
> +                intent.putExtra("DIARY_IDX", diaries[adapterPosition].idx)
네,
반영했습니다.

2019-06-20 05:37 UTC, merged